# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ckFyabJ4KTatwNXDPJFtqZ8cyK51Jk43
"""

name=str(input("Enter your name:"))
age=int(input("Enter your age:"))
city=str(input("Enter your city:"))
dict={'name':name,"age":age,"city":city}
print(f"My name is {dict['name']},I am {dict['age']} years old and I live in the city of {dict['city']}.")